package export

import (
	"fmt"
	"strings"
)

// readmeMD renders readme.md, the project's front door: what the system is,
// every token family the sheet emits (enumerated from the same tables the
// CSS emitter renders from, so the two cannot drift), ADR-007's step
// purposes, pointers to the foundation pages, and the reproducibility
// contract theme.json carries.
func readmeMD(s Snapshot) string {
	var b strings.Builder

	b.WriteString("# Vibrant Gio — design tokens\n\n")
	fmt.Fprintf(&b, "Vibrant Gio is a generative design system for [Gio](https://gioui.org) desktop\n"+
		"applications. The entire colour system derives from one brand seed — currently\n"+
		"`%s` — through `spectrum/tokens.FromSeed`: every colour role carries a\n"+
		"**nine-step functional ramp (100–900)** on a shared lightness scale, with the\n"+
		"role's **base pinned separately** so the brand colour is reproduced exactly, and\n"+
		"**dark mode is the paired ramp** — the same step keeps the same job in both\n"+
		"modes, so nothing is assigned twice (ADR-007). The contrast gate is APCA\n"+
		"(step 900 reaches |Lc| 90 and step 700 |Lc| 60 over the 100/200 grounds, every\n"+
		"pin's on-colour |Lc| 60 over its pin); WCAG 2 ratios are reported alongside but\n"+
		"do not gate.\n\n", hexRGB(s.Seed))

	b.WriteString("This directory is generated by `spectrum/export` (`cmd/vg-tokens`); do not edit\n" +
		"it by hand — regenerate it.\n\n")

	b.WriteString("## Files\n\n" +
		"- `styles.css` — the token sheet: one `:root` block (light colours plus every\n" +
		"  mode-invariant scale) and one `.dark` class override block (the paired dark\n" +
		"  colours only). Add `class=\"dark\"` to the root element to switch modes.\n" +
		"- `theme.json` — the generative parameters; see the reproducibility contract\n" +
		"  below.\n" +
		"- `foundations/color.html` — every ramp, pin, step purpose and measured\n" +
		"  APCA Lc / WCAG ratio per text pair, in both modes.\n" +
		"- `foundations/type.html` — every type role at its real metrics.\n" +
		"- `foundations/layout.html` — the spacing, radius and elevation scales as\n" +
		"  rendered specimens.\n\n" +
		"Each page reads only from `styles.css` — every styled value is a `var(--…)`\n" +
		"reference — and carries a light/dark toggle. Annotation numbers are printed for\n" +
		"both modes, labelled `L` and `D`.\n\n")

	b.WriteString("## Token families\n\n")
	b.WriteString("| Family | Tokens | Notes |\n| --- | --- | --- |\n")
	for _, role := range rampRoles {
		fmt.Fprintf(&b, "| `--color-%[1]s-<step>` | `--color-%[1]s-100` … `--color-%[1]s-900` | the %[1]s ramp; steps in hundreds |\n", role.name)
	}
	pinNames := make([]string, len(pinRoles))
	for i, pin := range pinRoles {
		pinNames[i] = "`--color-" + pin.name + "`"
	}
	fmt.Fprintf(&b, "| pins & semantic layer | %s | pinned bases, their on-colours, and the ramp-resolved surface/divider |\n", strings.Join(pinNames, ", "))
	b.WriteString("| `--font-family` | `--font-family` | the typeface every role uses |\n")
	typeNames := make([]string, len(typeRoles))
	for i, role := range typeRoles {
		typeNames[i] = role.name
	}
	fmt.Fprintf(&b, "| `--font-<role>-*` | roles %s; each with `-size`, `-line-height`, `-weight`, `-tracking` | px sizes, CSS numeric weights |\n", strings.Join(typeNames, ", "))
	fmt.Fprintf(&b, "| `--space-<key>` | %s | the 4-pt spacing grid, px |\n", joinTokens("--space-", spaceNames()))
	fmt.Fprintf(&b, "| `--radius-<key>` | %s | corner radii, Tailwind naming, px |\n", joinTokens("--radius-", radiusNames()))
	fmt.Fprintf(&b, "| `--shadow-<level>` | %s | box-shadow elevation approximations; E2.1/E5.1 remap these to surface roles |\n\n", joinTokens("--shadow-", elevationNames()))

	b.WriteString("## Step purposes (ADR-007)\n\n" +
		"| Step | Job |\n| --- | --- |\n" +
		"| 100 | tinted fill · app ground |\n" +
		"| 200 | tinted fill · card / raised surface |\n" +
		"| 300 | hover · subtle border, separator |\n" +
		"| 400 / 600 / 800 | intermediate steps; interaction states walk through them |\n" +
		"| 500 | mid-value reference · strong border |\n" +
		"| 700 | low-contrast text (Lc ≥ 60) · pressed |\n" +
		"| 900 | high-contrast body text (Lc ≥ 90) · pressed |\n\n" +
		"The pinned base — not a ramp step — is the solid fill; hover and pressed on a\n" +
		"solid walk one and two steps from the pin toward 900.\n\n")

	b.WriteString("## Reproducibility\n\n" +
		"`theme.json` records the seed (hex plus its OKLCh hue and sat), the pinned role\n" +
		"hexes per mode, the faces, the base radius and the measured lightness scales.\n" +
		"`FromSeed(seed)` regenerates every ramp and pin from the seed alone — a\n" +
		"round-trip test in `spectrum/export` asserts it — so the file, not this text,\n" +
		"is the contract. To rebrand, rerun `vg-tokens -seed #rrggbb`; every page here\n" +
		"reflows because nothing in them is hard-coded.\n\n" +
		"Fonts: the tokens name " + s.Typography.BodyLarge.Typeface + "; the pages fall back to system faces when it\n" +
		"is not installed. Density and the motion set are not exported yet (E5.1).\n")

	return b.String()
}

// spaceNames, radiusNames and elevationNames list each scale's key names in
// sheet order, for the readme's enumerations.
func spaceNames() []string {
	names := make([]string, len(spaceKeys))
	for i, k := range spaceKeys {
		names[i] = k.name
	}
	return names
}

func radiusNames() []string {
	names := make([]string, len(radiusKeys))
	for i, k := range radiusKeys {
		names[i] = k.name
	}
	return names
}

func elevationNames() []string {
	names := make([]string, len(elevationLevels))
	for i, k := range elevationLevels {
		names[i] = k.name
	}
	return names
}

// joinTokens renders a comma-separated code list of prefix+name tokens.
func joinTokens(prefix string, names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = "`" + prefix + n + "`"
	}
	return strings.Join(out, ", ")
}
